### PR TITLE
Exceptions everywhere

### LINKED ISSUE #1: ConnectionException is not actually thrown anywhere
According to the docs it should be thrown in the constructor :)

### LINKED ISSUE #2: Implement BranchNotFoundException
Rather than an unspecific `RuntimeException` :)

### LINKED ISSUE #3: Add a general ExceptionInterface
Should make things easier if multiple calls are made in the same code:

```php
try {
    $repo = new Repository('ssh://.....git');
    $branch = $repo->getBranch('main');
} catch (use Ausi\RemoteGit\ExceptionInterface) {
    // Do not care which one it is, just something with the connection or branch does not fit.
}
```

### PR DESCRIPTION
**Pull request by Toflar**
Fixes https://github.com/ausi/remote-git/issues/1
Fixes https://github.com/ausi/remote-git/issues/2
Fixes https://github.com/ausi/remote-git/issues/3

### CODE REVIEW

**Comment by ausi** [comment]
@Toflar agree with my changes from a6919e3b7b7440b15c60519144d989ceea8e9dd6 ?

File: src/Repository.php [hunk 1]
```diff
@@ -197,13 +213,25 @@ public function setConfig(string $key, string $value): static
 		return $this;
 	}
 
+	/**
+	 * @throws ConnectionException
```
Comment (ausi) [inline src/Repository.php:217]:
```suggestion
	 * @throws ConnectionException
	 * @throws InitializeException
```

**Comment by Toflar** [comment]
LGTM!
